"""ISO-3166 alpha-3 country code -> continent mapping.

Derived from Natural Earth 50m admin-0 countries (ISO_A3/ADM0_A3 fields);
seven hand-patched entries for territories Natural Earth codes oddly
(Bonaire, Christmas Island, Maldives, Mauritius, St Helena, Seychelles,
Netherlands Antilles). Covers every ISO code present in the OWID CO2 data.

Usage:
    from continents import CONTINENT_BY_ISO
    df["continent"] = df["iso_code"].map(CONTINENT_BY_ISO).fillna("Other")
"""

CONTINENT_BY_ISO = {
    "ABW": "North America",
    "AFG": "Asia",
    "AGO": "Africa",
    "AIA": "North America",
    "ALA": "Europe",
    "ALB": "Europe",
    "AND": "Europe",
    "ANT": "North America",
    "ARE": "Asia",
    "ARG": "South America",
    "ARM": "Asia",
    "ASM": "Oceania",
    "ATA": "Antarctica",
    "ATG": "North America",
    "AUS": "Oceania",
    "AUT": "Europe",
    "AZE": "Asia",
    "BDI": "Africa",
    "BEL": "Europe",
    "BEN": "Africa",
    "BES": "North America",
    "BFA": "Africa",
    "BGD": "Asia",
    "BGR": "Europe",
    "BHR": "Asia",
    "BHS": "North America",
    "BIH": "Europe",
    "BLM": "North America",
    "BLR": "Europe",
    "BLZ": "North America",
    "BMU": "North America",
    "BOL": "South America",
    "BRA": "South America",
    "BRB": "North America",
    "BRN": "Asia",
    "BTN": "Asia",
    "BWA": "Africa",
    "CAF": "Africa",
    "CAN": "North America",
    "CHE": "Europe",
    "CHL": "South America",
    "CHN": "Asia",
    "CIV": "Africa",
    "CMR": "Africa",
    "COD": "Africa",
    "COG": "Africa",
    "COK": "Oceania",
    "COL": "South America",
    "COM": "Africa",
    "CPV": "Africa",
    "CRI": "North America",
    "CUB": "North America",
    "CUW": "North America",
    "CXR": "Oceania",
    "CYM": "North America",
    "CYP": "Asia",
    "CZE": "Europe",
    "DEU": "Europe",
    "DJI": "Africa",
    "DMA": "North America",
    "DNK": "Europe",
    "DOM": "North America",
    "DZA": "Africa",
    "ECU": "South America",
    "EGY": "Africa",
    "ERI": "Africa",
    "ESH": "Africa",
    "ESP": "Europe",
    "EST": "Europe",
    "ETH": "Africa",
    "FIN": "Europe",
    "FJI": "Oceania",
    "FLK": "South America",
    "FRA": "Europe",
    "FRO": "Europe",
    "FSM": "Oceania",
    "GAB": "Africa",
    "GBR": "Europe",
    "GEO": "Asia",
    "GGY": "Europe",
    "GHA": "Africa",
    "GIN": "Africa",
    "GMB": "Africa",
    "GNB": "Africa",
    "GNQ": "Africa",
    "GRC": "Europe",
    "GRD": "North America",
    "GRL": "North America",
    "GTM": "North America",
    "GUM": "Oceania",
    "GUY": "South America",
    "HKG": "Asia",
    "HND": "North America",
    "HRV": "Europe",
    "HTI": "North America",
    "HUN": "Europe",
    "IDN": "Asia",
    "IMN": "Europe",
    "IND": "Asia",
    "IRL": "Europe",
    "IRN": "Asia",
    "IRQ": "Asia",
    "ISL": "Europe",
    "ISR": "Asia",
    "ITA": "Europe",
    "JAM": "North America",
    "JEY": "Europe",
    "JOR": "Asia",
    "JPN": "Asia",
    "KAZ": "Asia",
    "KEN": "Africa",
    "KGZ": "Asia",
    "KHM": "Asia",
    "KIR": "Oceania",
    "KNA": "North America",
    "KOR": "Asia",
    "KWT": "Asia",
    "LAO": "Asia",
    "LBN": "Asia",
    "LBR": "Africa",
    "LBY": "Africa",
    "LCA": "North America",
    "LIE": "Europe",
    "LKA": "Asia",
    "LSO": "Africa",
    "LTU": "Europe",
    "LUX": "Europe",
    "LVA": "Europe",
    "MAC": "Asia",
    "MAF": "North America",
    "MAR": "Africa",
    "MCO": "Europe",
    "MDA": "Europe",
    "MDG": "Africa",
    "MDV": "Asia",
    "MEX": "North America",
    "MHL": "Oceania",
    "MKD": "Europe",
    "MLI": "Africa",
    "MLT": "Europe",
    "MMR": "Asia",
    "MNE": "Europe",
    "MNG": "Asia",
    "MNP": "Oceania",
    "MOZ": "Africa",
    "MRT": "Africa",
    "MSR": "North America",
    "MUS": "Africa",
    "MWI": "Africa",
    "MYS": "Asia",
    "NAM": "Africa",
    "NCL": "Oceania",
    "NER": "Africa",
    "NFK": "Oceania",
    "NGA": "Africa",
    "NIC": "North America",
    "NIU": "Oceania",
    "NLD": "Europe",
    "NOR": "Europe",
    "NPL": "Asia",
    "NRU": "Oceania",
    "NZL": "Oceania",
    "OMN": "Asia",
    "PAK": "Asia",
    "PAN": "North America",
    "PCN": "Oceania",
    "PER": "South America",
    "PHL": "Asia",
    "PLW": "Oceania",
    "PNG": "Oceania",
    "POL": "Europe",
    "PRI": "North America",
    "PRK": "Asia",
    "PRT": "Europe",
    "PRY": "South America",
    "PSE": "Asia",
    "PYF": "Oceania",
    "QAT": "Asia",
    "ROU": "Europe",
    "RUS": "Europe",
    "RWA": "Africa",
    "SAU": "Asia",
    "SDN": "Africa",
    "SEN": "Africa",
    "SGP": "Asia",
    "SHN": "Africa",
    "SLB": "Oceania",
    "SLE": "Africa",
    "SLV": "North America",
    "SMR": "Europe",
    "SOM": "Africa",
    "SPM": "North America",
    "SRB": "Europe",
    "SSD": "Africa",
    "STP": "Africa",
    "SUR": "South America",
    "SVK": "Europe",
    "SVN": "Europe",
    "SWE": "Europe",
    "SWZ": "Africa",
    "SXM": "North America",
    "SYC": "Africa",
    "SYR": "Asia",
    "TCA": "North America",
    "TCD": "Africa",
    "TGO": "Africa",
    "THA": "Asia",
    "TJK": "Asia",
    "TKM": "Asia",
    "TLS": "Asia",
    "TON": "Oceania",
    "TTO": "North America",
    "TUN": "Africa",
    "TUR": "Asia",
    "TUV": "Oceania",
    "TWN": "Asia",
    "TZA": "Africa",
    "UGA": "Africa",
    "UKR": "Europe",
    "URY": "South America",
    "USA": "North America",
    "UZB": "Asia",
    "VAT": "Europe",
    "VCT": "North America",
    "VEN": "South America",
    "VGB": "North America",
    "VIR": "North America",
    "VNM": "Asia",
    "VUT": "Oceania",
    "WLF": "Oceania",
    "WSM": "Oceania",
    "YEM": "Asia",
    "ZAF": "Africa",
    "ZMB": "Africa",
    "ZWE": "Africa",
}
